version: '3'
services:
  web:
    image: why2pac/dp4p:0.9.4.13-py34
    ports:
      - "8000:8000"
    volumes:
      - /data/app
    build:
      context: ./

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest # nginx 서비스에서 사용할 도커 이미지
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
    links:
      - web:web
    depends_on: # 서비스 간의 종속성 표현
      - web